# Generated by Django 4.2.11 on 2024-07-31 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderFreelanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='Номер заказа')),
                ('order_type', models.CharField(choices=[('model', 'Заказ на модель'), ('model_print', 'Заказ на модель с печатью')], max_length=20, verbose_name='Тип заказа')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('our_model', models.BooleanField(default=True, verbose_name='Наша модель')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_orders', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Фриланс',
                'verbose_name_plural': 'Фриланс',
                'db_table': 'freelance_order',
            },
        ),
    ]
