# Generated by Django 4.2.11 on 2024-07-31 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0002_orderfreelancemodel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderfreelancemodel',
            name='order_type',
            field=models.CharField(choices=[('1', 'Заказ на модель'), ('2', 'Заказ на модель с печатью')], max_length=1, verbose_name='Тип заказа'),
        ),
    ]
