# Generated by Django 4.2.11 on 2024-06-09 17:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
                'db_table': 'material',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=500, unique=True, verbose_name='Имя файла')),
                ('height', models.FloatField(verbose_name='Высота')),
                ('width', models.FloatField(verbose_name='Ширина')),
                ('length', models.FloatField(verbose_name='Длина')),
                ('status', models.IntegerField(choices=[(0, 'не проверено'), (1, 'активно'), (2, 'забанено'), (3, 'нельзя удалять или отключать')], default=0)),
                ('materials', models.ManyToManyField(to='files.material')),
                ('owners', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Владельцы')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'db_table': 'file',
                'ordering': ['-filename'],
                'indexes': [models.Index(fields=['filename'], name='filename_idx'), models.Index(fields=['status'], name='status_idx')],
            },
        ),
    ]
