# Generated by Django 4.2.11 on 2024-06-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='description',
            field=models.TextField(default=344, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='name',
            field=models.CharField(default=34, max_length=500, unique=True, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
