# Generated by Django 4.2.11 on 2024-06-09 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0002_material_description_material_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescriptionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('line_video', models.TextField(verbose_name='Ссылка на видео')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description_file', to='files.file', verbose_name='File')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Описание файла',
                'verbose_name_plural': 'Описание файла',
                'db_table': 'description_file',
                'ordering': ['-title', '-file'],
                'indexes': [models.Index(fields=['title'], name='description_title_d32e6e_idx'), models.Index(fields=['description'], name='description_descrip_f1bbdc_idx')],
            },
        ),
    ]
