# Generated by Django 4.2.11 on 2024-06-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_descriptionfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descriptionfile',
            name='line_video',
            field=models.URLField(verbose_name='Ссылка на видео'),
        ),
    ]
