# Generated by Django 4.2.11 on 2024-06-09 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_alter_descriptionfile_line_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='file_image', verbose_name='Изображение')),
                ('description_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_file', to='files.descriptionfile', verbose_name='File')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'db_table': 'image_file',
            },
        ),
    ]
