# Generated by Django 4.2.11 on 2024-06-10 12:30

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='files.tags', verbose_name='Родительская категория'),
        ),
    ]
