# Generated by Django 4.2.11 on 2024-06-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_alter_tags_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='descriptionfile',
            name='tags',
            field=models.ManyToManyField(blank=True, to='files.tags', verbose_name='Теги'),
        ),
    ]
