# Generated by Django 4.2.11 on 2024-06-17 07:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0010_alter_imagefile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='descriptionfile',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время добавления'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время добавления'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tags',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время добавления'),
            preserve_default=False,
        ),
    ]
