# Generated by Django 4.2.11 on 2024-06-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0011_descriptionfile_time_create_file_time_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descriptionfile',
            name='time_create',
            field=models.BigIntegerField(blank=True, verbose_name='Время добавления'),
        ),
        migrations.AlterField(
            model_name='file',
            name='time_create',
            field=models.BigIntegerField(blank=True, verbose_name='Время добавления'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='time_create',
            field=models.BigIntegerField(blank=True, verbose_name='Время добавления'),
        ),
    ]
