# Generated by Django 4.2.11 on 2024-07-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField(verbose_name='ID заказчика')),
                ('delivery_type', models.IntegerField(choices=[('1', 'Самовывоз'), ('2', 'Доставка на адрес')], verbose_name='Тип доставки')),
                ('street', models.CharField(max_length=255, verbose_name='Улица')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Индекс')),
                ('delivery_deadline', models.TextField(verbose_name='Сроки доставки')),
                ('self_pickup_hours', models.TextField(blank=True, null=True, verbose_name='Когда работает')),
            ],
            options={
                'verbose_name': 'Заказчик',
                'verbose_name_plural': 'Заказчики',
                'db_table': 'order_customer',
            },
        ),
    ]
