# Generated by Django 4.2.11 on 2024-07-16 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(verbose_name='Продукт id')),
                ('height', models.FloatField(verbose_name='Высота')),
                ('width', models.FloatField(verbose_name='Ширина')),
                ('length', models.FloatField(verbose_name='Длина')),
                ('materials', models.TextField(verbose_name='Материал')),
                ('deadlines', models.TextField(verbose_name='Сроки выполнения')),
                ('delivery_terms', models.TextField(verbose_name='Сроки доставки')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'db_table': 'order_product',
            },
        ),
        migrations.AlterField(
            model_name='customer',
            name='delivery_type',
            field=models.IntegerField(choices=[(1, 'Самовывоз'), (2, 'Доставка на адрес')], verbose_name='Тип доставки'),
        ),
    ]
