# Generated by Django 4.2.11 on 2024-07-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_product_alter_customer_delivery_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('currency', models.CharField(max_length=100, verbose_name='Валюта')),
                ('production_cost', models.FloatField(verbose_name='Стоимость изготовления')),
                ('cost_delivery', models.FloatField(verbose_name='Стоимость доставки')),
                ('order', models.BooleanField(default=False, verbose_name='Заказ заказан или нет')),
                ('margin', models.FloatField(verbose_name='Маржа')),
            ],
            options={
                'verbose_name': 'Цена товара',
                'verbose_name_plural': 'Цена товаров',
                'db_table': 'order_price_product',
            },
        ),
    ]
