# Generated by Django 4.2.11 on 2024-07-17 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_order', models.CharField(choices=[(1, 'Отложенный'), (2, 'Ждет выбора исполнителя'), (3, 'В печати'), (4, 'Готов'), (5, 'Просрочен в печати'), (6, 'Выполнен'), (7, 'Отменен')], max_length=255, verbose_name='Статус')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.customer')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.delivery')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.executor')),
                ('price_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orders.priceproduct')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.product')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'order',
            },
        ),
    ]
